### ISSUE TITLE
goerli.etherscan.io support

### ISSUE THREAD

**Issue by abhayks1** [gnosis/verify-on-etherscan#1]
Hi Team,

Thank you for awesome library to verify contracts on etherscan. It's very useful.
Our DAPPs are deployed on mainnet, ropsten and goerli network. 

As per readms/docs there is no goerli support. 
What is the scheduled plan to support contracts verification on https://goerli.etherscan.io

Thank you in advance.

**Comment by Velenir** [comment]
So etherscan added verification for goerli? Great! It wasn't available back then.

Added support in c0f7adbf8cfcc5d9b61fb2d4b5cb6bfd3326693c

Tell me how it works for you

**Comment by abhayks1** [comment]
Really great 💯
Thank you for super quick response.
I am integrating it today. Will let you know if I face any issue.
